POST http://localhost:3001/articulosInsumo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyN2Q5MTIxZTFhZmFhZjc3ODFjMWRkMyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjUzODU1NTMyLCJleHAiOjE2NTQwMjgzMzJ9._2owQD6GimPFyNqzMCiU7lasrDSxm_23bM3lmLNn82A

{
    "rubro":"gaseosas",
    "denominacion":"coca 500ml",
    "precioCompra":"100",
    "stockActual":"200",
    "unidadMedida":"mililitros",
    "esInsumo":true
} 

