POST http://localhost:3001/articulosInsumo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyN2Q5MTIxZTFhZmFhZjc3ODFjMWRkMyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiaWF0IjoxNjUzNTA5MTQ4LCJleHAiOjE2NTM2ODE5NDh9.LiWHbejH7eSy1tr30t7tNAN6JJ-gJ5wrVIG0LmAhwns

{
    "rubro":"ingredientes",
    "denominacion":"harina",
    "precioCompra":"700",
    "stockActual":"5000",
    "unidadMedida":"gramos"
} 

